### ISSUE TITLE
Can't open the add/remove medicine stock dialog

### ISSUE THREAD

**Issue by otaconix** [citiususc/calendula#134]
# Version

2.5.7 from F-Droid

# Steps to reproduce

1. Edit a medicine
1. Tap the '+' or '-' button

# Expected outcome

The add/remove dialog gets displayed.

# Actual outcome

I get kicked back to the medicine screen.

## Exception

```
FATAL EXCEPTION: main
Process: es.usc.citius.servando.calendula, PID: 6220
java.lang.IllegalStateException: Fragment b{f3e5022 #0 number_dialog} declared target fragment MedicineCreateOrEditFragment{8239cfe #0 id=0x7f0901de android:switcher:2131296734:0} that does not belong to this FragmentManager!
	at android.support.v4.app.p.a(Unknown Source:303)
	at android.support.v4.app.p.e(Unknown Source:38)
	at android.support.v4.app.p.a(Unknown Source:45)
	at android.support.v4.app.d.g(Unknown Source:169)
	at android.support.v4.app.p.b(Unknown Source:38)
	at android.support.v4.app.p.a(Unknown Source:112)
	at android.support.v4.app.p.b(Unknown Source:89)
	at android.support.v4.app.p.f(Unknown Source:21)
	at android.support.v4.app.p$1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by mlaradji** [comment]
I can confirm that this issue is happening to me as well, though in my case the Calendula app completely crashes when trying to add stock via the +/-. As far as I can tell, this bug only appeared after upgrading Calendula to 2.5.7.

## Relevant Information
Calendula: 2.5.7 (38) from F-Droid
Phone: Samsung A5 2017
OS: Android 8.0.0

Reproducible: Always

**Comment by ontherunvaro** [comment]
@mlaradji It's been fixed in https://github.com/citiususc/calendula/commit/ca4d7b6c9d24bfc99adefab2060edadf06d4e7c7 , and it will be in the next release. Thanks for your feedback.
